version: '3.7'
services:
#PHP Service
 app:
  build:
   context: .
   dockerfile: Dockerfile
  image: php_service
  container_name: app
  restart: always
  tty: true
  environment:
   SERVICE_NAME: app
   SERVICE_TAGS: dev
  working_dir: /var/www
  volumes:
   - ./:/var/www
   - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
  networks:
   - app-network
#Nginx Service
 webserver:
  image: nginx:alpine
  container_name: webserver
  restart: always
  tty: true
  ports:
   - "88:80"
   - "443:443"
  volumes:
   - ./:/var/www
   - ./nginx/conf.d/:/etc/nginx/conf.d/
  networks:
   - app-network
#MySQL Service
 db:
  image: mysql
  container_name: db
  restart: always
  tty: true
  ports:
   - "5555:3306"
  environment:
   MYSQL_DATABASE: laravel
   MYSQL_USER: laravel
   MYSQL_PASSWORD: GRLJXBdS6V6zEtRDYFRRjwF6cm4hgWBr
   MYSQL_ROOT_PASSWORD: GRLJXBdS6V6zEtRDYFRRjwF6cm4hgWBr
   SERVICE_TAGS: dev
   SERVICE_NAME: mysql
  networks:
   - app-network
#PHPMyAdmin Service
 phpmyadmin:
  container_name: phpmyadmin
  image: phpmyadmin/phpmyadmin
  ports:
   - "7000:80"
  links:
   - db:db
  environment:
   MYSQL_USER: root
   MYSQL_PASSWORD: GRLJXBdS6V6zEtRDYFRRjwF6cm4hgWBr
   MYSQL_ROOT_PASSWORD: GRLJXBdS6V6zEtRDYFRRjwF6cm4hgWBr
   UPLOAD_LIMIT: 3000000000
  networks:
   - app-network
#Docker Networks
networks:
 app-network:     
  driver: bridge
#Volumes
volumes:
 lbdata:
  driver: local

